---
title: "Lab Due 2023-04-25 (Factors)"
author: "Jesse"
date: "2023-04-25"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---
### Load my Libraries
```{r libraries, echo=TRUE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
```

### Data Wrangling

```{r data, echo=TRUE, warning=FALSE}
data <- read_csv(here("Week_11","data", "intertidaldata.csv")) #read in my csv file & create an object for it

clean_intertidal <- data %>% #create an object for data wrangling
  mutate(Stars=`Stars (Counts)`, #rename each of these columns to keep names consistent
         Crabs=`Crabs (Counts)`,
         Whelks=`Whelks (Counts)`,
         Bare_Rock=`Bare Rock`, #rename these columns that have a space to have an underscore instead
         Small_Barnacles=`Small Barnacles`,
         Large_Barnacles= `Large Barnacles`,
         Gooseneck_Barnacles= `Gooseneck Barnacles`) %>% 
  mutate("Tide_Height"=fct_recode(Quadrat, "Low"="Low  .", #rename "Quadrat" to "Tide_Height" and then change these factors to be named properly
"Low"="Low ", #just adding these arguments in case these common mistakes were made (removing an extra space before or after the text)
"Mid"="Mid ",
"High"="High ",
"Mid"="Mid  1",
"Low"="Low  .",
"Low"=" Low",
"Mid"=" Mid",
"High"=" High")) %>% 
  select(Stars, Crabs, Whelks, Site, Transect, Tide_Height, Bare_Rock, Algae, Small_Barnacles, Large_Barnacles, Gooseneck_Barnacles, Anemone) %>%  #select only these columns
  filter(Site %in% c("Shell Beach", "Hazards", "Dana Point", "Cape Meares")) #filter my sites so that I only have the ones that I included
```
### Make a Plot

```{r plot, echo=TRUE, warning=FALSE}
ggplot()+
  geom_col(data=clean_intertidal, aes(x=Tide_Height, y=Crabs, fill=Site))+ #select the clean_intertidal dataframe and Tide_Height as my x axis, Number of Crabs as my y axis, and fill color representing Site
  facet_wrap(~Site)+ #create sub-plots based on Site (location)
  scale_x_discrete(limits=c("Low","Mid","High"))+ #order my x axis categories by Low, then Mid, then High
  labs(title="Number of Crabs by Site and Tide Height", #This is my plot title
       x="Tide Height", #this is my x axis title
       y="Number of Crabs Seen")+ #this is my y axis title
  theme(plot.title=element_text(hjust=0.5)) #centering my plot title
ggsave(here("Week_11","output","Plot.png")) #saving my plot to this pathway
```

